# 現状無効。今後実装予定。

# まずこれを動くようにする
# 挙動は同じ
# リファクタリングするイメージ
mission_name = "右に歩け！" # まず割り切って直接書く。後で揉み
mission      = "右"         # 〃

lever_toml      = "lever.toml"
bits_named_toml = "bits_named.toml"

###############
# あとでこちらに移行する

[[missions]]
mission = "右"

[[missions]]
mission = "A"

[[missions]]
mission = "RS + B"
